### ISSUE TITLE
Write Readme/Documentation

### ISSUE THREAD

**Issue by amur-tiger** [amur-tiger/ffn-parser#7]
* Readme should have proper title
* Readme should have badges
  * CI status with link to CI run
  * Badge with number of issues
  * npmjs status with link to npmjs
* Readme should have overview what this project does
* Readme should have installation instructions
* Readme should have usage instructions

**Comment by lschierer** [comment]
installation instructions would really help.

**Comment by amur-tiger** [comment]
I've added a bit more to the readme, hope this helps.
